/*
 * Download the three OFL faces from Google Fonts and serve them from our own
 * origin. Run once, then again only when a face is updated:  npm run fonts
 *
 * Self hosting rather than the CDN, for three reasons that all point the same
 * way. HTTP cache partitioning since Chrome 86 killed the shared-cache benefit,
 * so the CDN costs two extra third party connections and buys nothing. It also
 * carries a live GDPR question, which is the wrong risk to hold on a site
 * fronting a nonprofit. And the Google hosted builds are stripped, so this is
 * the only route to subsetting and stylistic sets later.
 *
 * All three faces are SIL OFL 1.1, which permits this. Their licence notices
 * are reproduced on /attributions, which the OFL requires.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const OUT_DIR = path.join(ROOT, 'public', 'fonts');
const CSS_OUT = path.join(ROOT, 'public', 'css', 'fonts.css');

// A modern UA is required, or Google serves the legacy truetype build.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36';

const FAMILIES = [
  { name: 'TASA Orbiter', spec: 'TASA+Orbiter:wght@400..800', file: 'tasa-orbiter', weight: '400 800', display: true },
  { name: 'Literata', spec: 'Literata:opsz,wght@7..72,300..700', file: 'literata', weight: '300 700', display: false },
  { name: 'Martian Mono', spec: 'Martian+Mono:wdth,wght@75..112.5,300..700', file: 'martian-mono', weight: '300 700', display: false, stretch: '75% 112.5%' },
];

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const blocks = [
    '/* GENERATED by scripts/fetch-fonts.mjs. Do not hand edit.',
    ' * All three faces are SIL OFL 1.1. See /attributions.',
    ' */',
    '',
  ];

  for (const fam of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${fam.spec}&display=swap`;
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`${fam.name}: HTTP ${res.status} from Google Fonts`);
    const css = await res.text();

    // Keep only the latin block. latin-ext, cyrillic and greek are dead weight
    // for this site and would triple the payload.
    const chunks = css.split('/*').filter((c) => c.trimStart().startsWith('latin *'));
    const chunk = chunks[0];
    if (!chunk) throw new Error(`${fam.name}: no latin subset found in the served CSS`);

    const src = /src:\s*url\((https:\/\/[^)]+\.woff2)\)/.exec(chunk);
    const range = /unicode-range:\s*([^;]+);/.exec(chunk);
    if (!src) throw new Error(`${fam.name}: no woff2 URL in the latin block`);

    const bin = Buffer.from(await (await fetch(src[1], { headers: { 'User-Agent': UA } })).arrayBuffer());
    const outName = `${fam.file}.woff2`;
    await writeFile(path.join(OUT_DIR, outName), bin);
    console.log(`${fam.name.padEnd(14)} ${(bin.length / 1024).toFixed(1).padStart(6)} KB  ${outName}`);

    blocks.push(
      '@font-face {',
      `  font-family: '${fam.name}';`,
      '  font-style: normal;',
      `  font-weight: ${fam.weight};`,
      fam.stretch ? `  font-stretch: ${fam.stretch};` : null,
      '  font-display: swap;',
      `  src: url('/static/fonts/${outName}') format('woff2');`,
      range ? `  unicode-range: ${range[1].trim()};` : null,
      '}',
      ''
    );
  }

  await writeFile(CSS_OUT, blocks.filter((l) => l !== null).join('\n'), 'utf8');
  console.log(`\nWrote ${path.relative(ROOT, CSS_OUT)}`);
  console.log('Add preload tags for the display and body faces only. Not the mono.');
}

main().catch((err) => {
  console.error(`\nFont fetch failed: ${err.message}`);
  console.error('The site still renders in the fallback stack, so this is not fatal.');
  process.exit(1);
});
