'use strict';

/*
 * Structured data and social cards.
 *
 * Both exist for the same reason: a link to this site is usually encountered
 * somewhere else first, in a recruiter's Slack, a LinkedIn message, a search
 * result. Preview crawlers fetch only the initial server rendered HTML and do
 * not execute JavaScript, which makes this server rendered stack an advantage
 * here rather than a compromise.
 */

const crypto = require('node:crypto');

const PERSON_ID = '#eric-dean';

/**
 * One stable @id reused on every page, so search engines merge this site, the
 * LinkedIn profile and the GitHub account into one entity rather than three.
 */
function personNode(siteUrl) {
  return {
    '@type': 'Person',
    '@id': siteUrl + '/' + PERSON_ID,
    name: 'Eric J. Dean',
    givenName: 'Eric',
    familyName: 'Dean',
    url: siteUrl + '/',
    jobTitle: 'Mechanical Engineering Student',
    affiliation: { '@type': 'CollegeOrUniversity', name: 'University of California, Los Angeles' },
    address: {
      '@type': 'PostalAddress',
      addressLocality: 'Half Moon Bay',
      addressRegion: 'CA',
      addressCountry: 'US',
    },
    knowsAbout: [
      'Mechanical design', 'CAD', 'Onshape', 'Fusion 360',
      'Electrical systems', 'Wiring harness fabrication', 'CAN bus',
      'Control systems', 'Swerve drive kinematics', 'Sensor fusion',
      'Java', 'TypeScript', 'Node.js', 'WPILib',
      'CNC machining', '3D printing',
      'Technical documentation', 'Nonprofit operations',
    ],
    sameAs: [
      'https://github.com/XrxcGH',
      'https://www.linkedin.com/in/edean07',
    ],
  };
}

function breadcrumbs(siteUrl, trail) {
  return {
    '@type': 'BreadcrumbList',
    itemListElement: trail.map((t, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: t.name,
      item: siteUrl + t.url,
    })),
  };
}

const STATUS_TO_STATE = {
  shipped: 'Published',
  competed: 'Published',
  'in-progress': 'Draft',
  specification: 'Draft',
  archived: 'Archived',
};

/**
 * SoftwareSourceCode only when software was the PRIMARY discipline, and
 * CreativeWork otherwise.
 *
 * Deliberately not "primary or significant". The Google Workspace package has
 * software as a significant discipline because its artefacts are generated by
 * Python, but it is a governance document set, not a code repository, and
 * typing it as source code would be a small lie told to a machine. Claiming
 * everything is software would also undercut the whole argument here, which is
 * that most of this work is not.
 */
function projectNode(siteUrl, p) {
  const isSoftware = (p.facets || []).some(
    (f) => f.slug === 'software' && f.weight === 'primary'
  );
  const node = {
    '@type': isSoftware ? 'SoftwareSourceCode' : 'CreativeWork',
    '@id': siteUrl + '/work/' + p.slug,
    url: siteUrl + '/work/' + p.slug,
    name: p.title,
    headline: p.title,
    abstract: p.subtitle || undefined,
    author: { '@id': siteUrl + '/' + PERSON_ID },
    creativeWorkStatus: STATUS_TO_STATE[p.status] || undefined,
    dateModified: p.updated_at || undefined,
    keywords: (p.facets || []).map((f) => f.label).join(', ') || undefined,
  };
  if (isSoftware) {
    const repo = (p.links || []).find((l) => l.kind === 'repo');
    if (repo) node.codeRepository = repo.url;
  }
  // Drop undefined keys: a node full of nulls validates but reads as noise.
  for (const k of Object.keys(node)) if (node[k] === undefined) delete node[k];
  return node;
}

/** One @graph per page rather than several script tags, which validates cleanly. */
function jsonLd(siteUrl, opts) {
  const o = opts || {};
  const graph = [personNode(siteUrl)];
  if (o.project) graph.push(projectNode(siteUrl, o.project));
  if (o.trail && o.trail.length) graph.push(breadcrumbs(siteUrl, o.trail));
  return JSON.stringify({ '@context': 'https://schema.org', '@graph': graph });
}

/* --------------------------------------------------------------- OG cards */

/*
 * Generated as SVG and rasterised on demand, then cached on disk. Deliberately
 * not a headless browser: that would be the heaviest dependency in the whole
 * project, for an image carrying six words.
 *
 * 1200 by 630 is the standard, and everything meaningful stays inside a
 * 1080 by 600 centre safe zone because several platforms crop.
 */
const OG_W = 1200;
const OG_H = 630;

const esc = (s) => String(s || '')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;').replace(/'/g, '&apos;');

/** Crude but adequate wrapping: these are short titles at a known size. */
function wrap(text, maxChars, maxLines) {
  const words = String(text || '').split(/\s+/).filter(Boolean);
  const lines = [];
  let line = '';
  for (const w of words) {
    if (!line) { line = w; continue; }
    if ((line + ' ' + w).length <= maxChars) {
      line += ' ' + w;
    } else {
      lines.push(line);
      line = w;
      if (lines.length === maxLines) { line = ''; break; }
    }
  }
  if (line && lines.length < maxLines) lines.push(line);
  return lines;
}

/**
 * The card is the site's own palette and the projection mark rather than a
 * screenshot. A screenshot at thumbnail size is illegible, which is why so
 * many of them are worse than nothing.
 */
function ogSvg(opts) {
  const o = opts || {};
  const lines = wrap(o.title, 26, 3);
  const size = lines.length >= 3 ? 66 : lines.length === 2 ? 80 : 92;
  const startY = 300 - ((lines.length - 1) * size * 0.56);
  const subLines = o.subtitle ? wrap(o.subtitle, 62, 2) : [];

  const titleEls = lines.map((l, i) =>
    '  <text x="90" y="' + Math.round(startY + i * size * 1.1) + '" fill="#F2F6F0" ' +
    'font-family="Helvetica, Arial, sans-serif" font-weight="700" font-size="' + size +
    '" letter-spacing="-2">' + esc(l) + '</text>'
  ).join('\n');

  const subEls = subLines.map((l, i) =>
    '  <text x="90" y="' + Math.round(startY + lines.length * size * 1.1 + 24 + i * 38) +
    '" fill="#9AA197" font-family="Georgia, serif" font-size="30">' + esc(l) + '</text>'
  ).join('\n');

  return [
    '<svg xmlns="http://www.w3.org/2000/svg" width="' + OG_W + '" height="' + OG_H + '" viewBox="0 0 ' + OG_W + ' ' + OG_H + '">',
    '  <rect width="' + OG_W + '" height="' + OG_H + '" fill="#111510"/>',
    '  <rect x="0" y="0" width="10" height="' + OG_H + '" fill="#FE852A"/>',
    '  <g transform="translate(870 92) scale(1.4)" fill="none" stroke="#393F36" stroke-width="7" stroke-linecap="butt" stroke-linejoin="miter">',
    '    <circle cx="42" cy="48" r="34"/>',
    '    <circle cx="42" cy="48" r="17"/>',
    '    <path d="M108 14 L164 30 L164 66 L108 82 Z"/>',
    '  </g>',
    '  <text x="90" y="130" fill="#FE852A" font-family="monospace" font-size="24" letter-spacing="6">' +
      esc(String(o.eyebrow || 'Eric J. Dean').toUpperCase()) + '</text>',
    titleEls,
    subEls,
    '  <text x="90" y="562" fill="#9AA197" font-family="monospace" font-size="21" letter-spacing="4">MECHANICAL / ELECTRICAL / CONTROLS / SOFTWARE</text>',
    '</svg>',
  ].filter(Boolean).join('\n');
}

/** Cache key derived from the content, so editing a title invalidates it. */
function ogKey(parts) {
  return crypto.createHash('sha256').update(JSON.stringify(parts)).digest('hex').slice(0, 16);
}

module.exports = {
  jsonLd, personNode, projectNode, breadcrumbs,
  ogSvg, ogKey, wrap, OG_W, OG_H, PERSON_ID,
};
